FROM cmosh/golang-arm:latest
RUN apk add -U git make curl
RUN go get github.com/Masterminds/glide
ENV DOCKER_VERSION 1.10.3
ENV APP interlock
ENV REPO cmosh/$APP

RUN curl -sL https://get.docker.com/builds/Linux/x86_64/docker-${DOCKER_VERSION} > /usr/local/bin/docker && \
    chmod +x /usr/local/bin/docker

WORKDIR /go/src/github.com/$REPO

COPY . /go/src/github.com/$REPO
